# .streamlit/secrets.toml
OPENAI_API_KEY = "YOUR_API_KEY"
SUPABASE_PASSWORD = "you-supabase-password" 
SUPABASE_USER = "you-supabase-user"
SUPABASE_HOST = "you-supabase-host"
SUPABASE_DB = "you-supabase-db"