supabase_api_url      = "https://api.supabase.io"
supabase_project_name = "llamaindex-streamlit"
supabase_org_id       = "mrgdqctdxpzwnsidahjb"
supabase_region       = "us-east-2"
github_owner          = "your-github-userna"
github_repo_name      = "llamaindex-streamlit"
